# Generated by Django 5.2.4 on 2026-05-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conto',
            name='tipo',
            field=models.CharField(choices=[('conto_corrente', 'Conto Corrente'), ('contanti', 'Contanti')], default='contanti', max_length=20),
        ),
    ]
