# Generated by Django 5.2.14 on 2026-05-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_globalsettings_registration_invite_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ui_settings',
            field=models.JSONField(blank=True, default=dict, help_text='User UI settings and preferences'),
        ),
    ]
